### ISSUE TITLE
Install creates "Module Mismatch" and Node Version mismatch. User goes in circles without an ability to resolve

### ISSUE THREAD

**Issue by sshadmand** [GoogleCloudPlatform/cloud-functions-emulator#126]
I have installed a plethora of versions of node and the emulator to try and satisfied the warning below. No matter how far back I go in alpha versions I get this error.

```
#> firebase serve --only functions

=== Serving from '/Users/seanshadmand/repos/konch/firebase_functions'...

⚠  functions: Cannot start emulator. Error: Module version mismatch. Expected 48, got 51.
```

My yarn install also gives the warning

```
[2/4] Fetching packages...
warning Pattern ["@google-cloud/functions-emulator@^1.0.0-alpha.22"] is trying to unpack in the same destination "/Users/seanshadmand/Library/Caches/Yarn/v1/npm-@google-cloud/functions-emulator-1.0.0-alpha.22-e045e578094b871f4e89a3c4fe001cd720cdf689" as pattern ["@google-cloud/functions-emulator@^1.0.0-alpha.19"]. This could result in a non deterministic behavior, skipping.
warning @google-cloud/functions-emulator@1.0.0-alpha.22: The engine "node" is incompatible with this module. Expected version ">=6.11.1".
info "@google-cloud/functions-emulator@1.0.0-alpha.22" is an optional dependency and failed compatibility check. Excluding it from installation.
error @google-cloud/functions-emulator@1.0.0-alpha.22: The engine "node" is incompatible with this module. Expected version ">=6.11.1".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

My node is at `v6.9.1`. When I upgrade to `v6.11.1` like it suggests I get this error:

```
#> firebase serve --only functions

=== Serving from '/Users/seanshadmand/repos/konch/firebase_functions'...

⚠  functions: Cannot start emulator. Please use Node version v6.9.1, you have v6.11.1

```

After going in circles, I thought maaaaaaybe this is a bug with the packages.

So in summary:
- Install node 6.9.1 and the latest emulator, you get Module version mismatch. "Expected 48, got 51."
- Upgrade node based on yarn installation message, you will get an unsupported node version mismatch.

**Comment by jasonge511** [comment]
I have the exact same two error messages and couldn't figure it out. I went back and installed a version package from when I thought firebase-tools was still on 6.9.1 and it didn't work either

**Comment by jasonge511** [comment]
I came to a solution, please see if this works for you, my friend:
https://github.com/firebase/firebase-tools/issues/415

**Comment by jmdobry** [comment]
`Error: Module version mismatch. Expected 48, got 51.` is an error that happens when a package with native bindings is installed with one version of Node, but then an attempt is made to run it with a different version Node. Native bindings currently can only be run by the version of Node with which they were installed. The Emulator depends on the `grpc` package which has native bindings.

The solution ought to be to completely remove any trace of the packages with native bindings from your system, then reinstall with the desired version of Node. This would include removing `node_modules` directories, and clearing npm/yarn caches.

If you're using the Emulator directly, I would try uninstalling it, clearing any npm/yarn cache, then re-running `npm install -g @google-cloud/functions-emulator` (and don't change versions of Node).

If the Emulator was installed via firebase-tools, you'll need to uninstall, clear cache, and reinstall firebase-tools.

Regarding the `functions: Cannot start emulator. Please use Node version v6.9.1, you have v6.11.1` from firebase-tools, this appears to have been fixed in the latest version of firebase-tools.

**Comment by sshadmand** [comment]
Thanks @jmdobry. Did a thourough cleaning of modules and cache and I no longer get the errors I posted. 

I am getting a new error:
```
i  functions: Preparing to emulate HTTPS functions. Support for other event types coming soon.
⚠  functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory. Please note that emulation of custom config values are not supported yet. Run firebase serve --only hosting to only serve hosting files.

FirebaseError: Error parsing triggers: Cannot find module '/Users/seanshadmand/repos/konch/firebase_functions/functions/node_modules/grpc/src/node/extension_binary/grpc_node.node'

Try running "npm install" in your functions directory before deploying.
i  functions: No HTTPS functions emulated. Support for other function types are coming soon.
```

I think I can work through it, but posting for posterity

**Comment by sshadmand** [comment]
Following up from above, I had already installed firebase-tools globally, but it seems like I had to add it to the project specifically too (based on the error), which threw me off. Not sure if I should have ever installed it globally in the first place.

All that being said, it works now. Thanks!
