### ISSUE TITLE
Issue with NodeJS Version

### ISSUE THREAD

**Issue by d0x7** [GoogleCloudPlatform/cloud-functions-emulator#155]
### Description

```SHELL
$ firebase serve --only functions

=== Serving from '******'...

i  functions: Preparing to emulate functions.
Warning: You're using Node.js v7.9.0 but Google Cloud Functions only supports v6.11.1.
```

After installing Node v6.11.1

```SHELL
$ firebase serve --only functions

=== Serving from '******'...

!  functions: Cannot start emulator. Please use Node version v6.9.1, you have v6.11.1
```

### Steps to reproduce

Install NodeJS v6.11.1

Thanks!

**Comment by d0x7** [comment]
This issue is kinda strange. I tried to install v6.9.1 as described and now I got the following error

```SHELL
$ firebase serve --only functions

=== Serving from '******'...

i  functions: Preparing to emulate functions.
Node.js v6.11.x or greater is required to run the Emulator!
!  functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory.
!  functions: Error from emulator. Error: Emulator crashed! Check the log file...
Shutting down...
```

What should I do?

**Comment by jmdobry** [comment]
You need to use Node.js v6.11.1 or newer.

See also [this comment](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/issues/156#issuecomment-344062555)

Also, because the emulator has a dependency on `grpc` which has native bindings, whenever you change the version of Node that you're using you need to completely uninstall the emulator (and firebase tools), and then re-install using your new Node.js version.

**Comment by jmdobry** [comment]
Please check out the [Troubleshooting Guide](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/wiki/Troubleshooting)

If it doesn't help, please comment back on this issue with more details steps to reproduce your error.
